# Toolhive operator subchart configuration
toolhive-operator:
  operator:
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 1Gi
    # OpenShift security context overrides - requires anyuid SCC
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000  # Will be overridden by anyuid SCC
      capabilities:
        drop:
        - ALL
    podSecurityContext:
      runAsNonRoot: true

# MCP servers configuration
mcp-servers:
  weather:
    # Weather MCP Server configuration
    enabled: true
    port: 8000
    targetPort: 8000
    transport: sse
    image: "quay.io/ecosystem-appeng/mcp-weather:0.1.0"
    permissionProfile:
      name: network
      type: builtin
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  hr:
    enabled: true
    port: 8000
    transport: sse
    image: "quay.io/rh-ai-quickstart/hr-mcp-server:latest"
    permissionProfile:
      name: network
      type: builtin
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    podSecurityContext:
      fsGroup: 0
      fsGroupChangePolicy: OnRootMismatch
      seccompProfile:
        type: RuntimeDefault
    
  
  oracle-sqlcl:
    # Oracle SQLcl MCP Server configuration
    # NOTE: Requires Oracle database and oracle23ai secret to exist
    enabled: false  # Oracle DB is available
    port: 8080
    transport: stdio
    image: "quay.io/ecosystem-appeng/oracle-sqlcl:0.1.0"
    permissionProfile:
      name: network
      type: builtin
    env:
      ORACLE_USER: "sales"
      ORACLE_PASSWORD: null  # Sourced from secret
      ORACLE_CONNECTION_STRING: null  # Sourced from secret
      ORACLE_CONN_NAME: oracle_connection
      JAVA_TOOL_OPTIONS: "-Djava.io.tmpdir=/sqlcl-home/tmp"
      _JAVA_OPTIONS: ""
      HOME: "/sqlcl-home"
    envSecrets:
      ORACLE_PASSWORD:
        name: oracle23ai
        key: password
      ORACLE_CONNECTION_STRING:
        name: oracle23ai
        key: jdbc-uri
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    podSecurityContext:
      fsGroup: 0
      fsGroupChangePolicy: OnRootMismatch
      seccompProfile:
        type: RuntimeDefault
    persistence:
      enabled: true
      volumeName: sqlcl-data
      accessMode: ReadWriteOnce
      size: 5Gi
      storageClassName: gp3-csi
    # Volume mounts for persistent storage
    volumeMounts:
      - name: sqlcl-data
        mountPath: /sqlcl-home
