# Default values for ingestion-pipeline.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/ecosystem-appeng/ingestion-pipeline
  pullPolicy: Always
  # Use Chart.AppVersion for image tag, so no need to set it here
  # tag: "0.2.8"

imagePullSecrets: []

serviceAccount:
  create: true
  automount: true

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

strategy:
  type: Recreate

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

args:
env: {}

resources: {}

autoscaling:
  enabled: false

# Additional volumes on the output Deployment definition.
volumes: {}

# Additional volumeMounts on the output Deployment definition.
volumeMounts: {}

nodeSelector: {}

tolerations: []

affinity: {}

# Multiple pipeline configurations
pipelines:
  # Default S3-based pipeline
  default-s3-pipeline:
    enabled: true
    # pipeline type - options are [S3, GITHUB, URL]
    source: S3
    # embedding model to use for creating embeddings
    embedding_model: "all-MiniLM-L6-v2"
    # name of the vector db with version, pipeline will be created with pipeline_red_hat_openshift
    name: "default-s3-pipeline"
    # version of the knowledgebase
    version: "1.0"
    vector_store_name: "demo-rag-vector-db-v1-0-s3"

    # Source configuration
    S3:
      access_key_id: minio_rag_user
      secret_access_key: minio_rag_password
      bucket_name: documents
      endpoint_url: http://minio:9000
      region: us-east-1

  # # GitHub-based pipeline
  # github-docs-pipeline:
  #   enabled: true
  #   source: GITHUB
  #   embedding_model: "all-MiniLM-L6-v2"
  #   name: "github-docs-vector-db"
  #   version: "1.0"
  #   vector_store_name: "github-docs-vector-db-v1-0-github"

  #   GITHUB:
  #     url: https://github.com/rh-ai-quickstart/RAG.git
  #     path: docs
  #     token: auth_token
  #     branch: main

  # # URL-based pipeline for web scraping
  # url-content-pipeline:
  #   enabled: true
  #   source: URL
  #   embedding_model: "all-MiniLM-L6-v2"
  #   name: "url-content-vector-db"
  #   version: "1.0"
  #   vector_store_name: "url-content-vector-db-v1-0-url"

  #   URL:
  #     urls:
  #       - "https://arxiv.org/pdf/2408.09869"
  #       - "https://raw.githubusercontent.com/docling-project/docling/main/tests/data/pdf/2305.03393v1-pg9.pdf"



authUser: ""

# generate provenance for the knowledge base
enableSigning: false